### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by RuskinTH** [ONCOJ/data#1]
There's a glitch where the TGrep2 search will give a non-zero number of hits but no results are displayed and the CSV file is empty. Example searches which trigger this include:
/VB-CONC/|/VB-ADN/|/VB-ADC/
(/VB-CONC/|/VB-ADN/|/VB-ADC/) << /wo$/
/pk/ara

**Comment by ajb129** [comment]
Your search expressions are not valid TGrep2 expressions. Try:

/(VB-CONC|VB-ADN|VB-ADC)/
/(VB-CONC|VB-ADN|VB-ADC)/ << /wo$/

The delimiter character (/) bounds a regular expression for matching nodes
and disjunction should be inside, see section 2.2. of: https://ajb129.github.io/tgrep2_guide.html

**Comment by ajb129** [comment]
I made some changes and now disjunction of node descriptions will work, so the original search expressions e.g.
(/VB-CONC/|/VB-ADN/|/VB-ADC/) << /wo$/
should now work. You can also now do things like
VB-CONC|VB-ADN|/VB-ADC/ << /wo$/
that is, combine simple character string node searches with regular expression node searches.
This is not necessarily search behaviour to encourage so I will leave it undocumented. It isn't compatible with Tregex search syntax for example. But this is one less gotcha to have to explain for the current interface.
