### ISSUE TITLE
https://oncoj.ninjal.ac.jp is dead

### ISSUE THREAD

**Issue by Chuterix** [ONCOJ/data#5]
Unable to connect

An error occurred during a connection to oncoj.ninjal.ac.jp.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

**Comment by ajb129** [comment]
Many thanks for the report. You should find oncoj.ninjal.ac.jp working now.
